export const UNKNOWN_SERVER_ERROR = 'SERVER.UNKNOWN_INTERNAL_SERVER_ERROR'
export const ENDPOINT_NOT_FOUND = 'SERVER.ENDPOINT_NOT_FOUND'
export const PRISMA_ENTITY_INVALID_BODY = 'PRISMA.ENTITY.INVALID_BODY'